import type { AppLocale } from "@/lib/i18n/config";
import type { LocalizedLabel } from "@/lib/stadium/stadium-types";

const stadiumMapMessages = {
  ro: {
    overviewTitle: "Overview stadion",
    overviewDescription:
      "Alege mai intai tribuna sau sectorul din harta, apoi continua cu selectia locurilor.",
    flowStepOverviewTitle: "1. Alege zona",
    flowStepOverviewDescription: "Porneste din harta stadionului sau direct din lista de tribune.",
    flowStepSectorTitle: "2. Alege sectorul",
    flowStepSectorDescription: "Deschide sectorul dorit si verifica rapid disponibilitatea.",
    flowStepSeatTitle: "3. Alege locurile",
    flowStepSeatDescription: "Atinge locurile disponibile pentru a le selecta.",
    flowStepCheckoutTitle: "4. Continua",
    flowStepCheckoutDescription:
      "Blocheaza temporar locurile, apoi confirma emiterea sau continua spre plata.",
    flowStepActive: "Activ",
    flowStepWaiting: "In asteptare",
    tribunesTitle: "Tribune",
    sectorsTitle: "Sectoare",
    seatMapTitle: "Harta sectorului",
    backToOverview: "Inapoi la stadion",
    backToTribune: "Inapoi la tribuna",
    selectedTribune: "Tribuna selectata",
    selectedSector: "Sector selectat",
    sectorUnavailable: "Sector indisponibil momentan",
    noSectorSelected: "Alege un sector din overview pentru a vedea locurile.",
    noSeatsAvailable: "Nu exista locuri afisabile pentru acest sector.",
    seatLegendAvailable: "Disponibil",
    seatLegendSelected: "Selectat",
    seatLegendHeld: "Blocat temporar",
    seatLegendSold: "Vandut / emis",
    seatLegendBlocked: "Blocat",
    mapLegendAvailable: "Bookabil",
    mapLegendLimited: "Capacitate redusa",
    mapLegendUnavailable: "Indisponibil",
    mapLegendHidden: "Ascuns",
    freeText: "Acces gratuit",
    row: "Rand",
    seat: "Loc",
    seats: "locuri",
    tapSeatHint:
      "Locurile disponibile pot fi selectate direct. Pe mobil poti glisa orizontal pe rand pentru a vedea toate locurile.",
    selectedSeatsCount: "locuri selectate",
    currentSector: "Sector curent",
    currentTribune: "Tribuna curenta",
    totalSeatsLabel: "locuri totale",
    availableNowLabel: "disponibile acum",
    continueAction: "Continua",
    selectSeatsFirst: "Selecteaza cel putin un loc pentru a continua.",
    activeHold: "Hold activ",
    available: "disponibile",
    held: "hold",
    reserved: "rezervate",
    blocked: "blocate",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    zoomReset: "Reset zoom",
    zoomHint: "Poti mari harta din butoane sau cu pinch pe ecranele tactile.",
    stadiumFallback:
      "Stadionul nu are inca o geometrie custom. Afisam o harta generata automat din sectoarele existente.",
  },
  ru: {
    overviewTitle: "Obzor stadiona",
    overviewDescription:
      "Snachala vyberi tribunu ili sektor na karte, potom perehodi k vyboru mest.",
    flowStepOverviewTitle: "1. Vyberi zonu",
    flowStepOverviewDescription: "Nachni s karty stadiona ili so spiska tribyun.",
    flowStepSectorTitle: "2. Vyberi sektor",
    flowStepSectorDescription: "Otkroi nuzhnyy sektor i bystro prover dostupnost.",
    flowStepSeatTitle: "3. Vyberi mesta",
    flowStepSeatDescription: "Nazhmi na dostupnye mesta, chtoby ih vybrat.",
    flowStepCheckoutTitle: "4. Prodolzhai",
    flowStepCheckoutDescription:
      "Vremenno zablokiruy mesta, zatem podtverdi vydachu ili pereidi k oplate.",
    flowStepActive: "Aktivno",
    flowStepWaiting: "Ozhidaet",
    tribunesTitle: "Tribuny",
    sectorsTitle: "Sektory",
    seatMapTitle: "Karta sektora",
    backToOverview: "Nazad k stadionu",
    backToTribune: "Nazad k tribune",
    selectedTribune: "Vybrannaya tribuna",
    selectedSector: "Vybrannyi sektor",
    sectorUnavailable: "Sektor vremenno nedostupen",
    noSectorSelected: "Vyberi sektor na obshchei karte, chtoby uvidet mesta.",
    noSeatsAvailable: "Dlya etogo sektora net otobrazhaemyh mest.",
    seatLegendAvailable: "Dostupno",
    seatLegendSelected: "Vybrano",
    seatLegendHeld: "Vremenno zablokirovano",
    seatLegendSold: "Prodano / vydano",
    seatLegendBlocked: "Zablokirovano",
    mapLegendAvailable: "Dostupen",
    mapLegendLimited: "Ogranicheno",
    mapLegendUnavailable: "Nedostupen",
    mapLegendHidden: "Skryt",
    freeText: "Besplatno",
    row: "Ryad",
    seat: "Mesto",
    seats: "mest",
    tapSeatHint:
      "Dostupnye mesta mozhno vybirat srazu. Na telefone mozhno prokruchivat ryad po gorizontali, chtoby uvidet vse mesta.",
    selectedSeatsCount: "vybrano mest",
    currentSector: "Tekushchiy sektor",
    currentTribune: "Tekushchaya tribuna",
    totalSeatsLabel: "mest vsego",
    availableNowLabel: "dostupno seychas",
    continueAction: "Prodolzhit",
    selectSeatsFirst: "Snachala vyberi hotya by odno mesto.",
    activeHold: "Aktivnyy hold",
    available: "dostupno",
    held: "hold",
    reserved: "zanyato",
    blocked: "zablokirovano",
    zoomIn: "Uvelichit",
    zoomOut: "Umenshit",
    zoomReset: "Sbrosit masshtab",
    zoomHint: "Masshtab mozhno menyat knopkami ili zhestom pinch na touch-ekranah.",
    stadiumFallback:
      "U stadiona poka net individualnoi geometrii. Pokazyvaem avtomaticheski sformirovannuyu kartu.",
  },
} as const;

export function getStadiumMapMessages(locale: AppLocale) {
  return stadiumMapMessages[locale] ?? stadiumMapMessages.ro;
}

export function getLocalizedLabel(
  locale: AppLocale,
  fallback: string,
  labels?: LocalizedLabel,
) {
  return labels?.[locale] ?? labels?.ro ?? labels?.ru ?? fallback;
}
